### ISSUE TITLE
Compile errors with ESP-IDF

### ISSUE THREAD

**Issue by mulcmu** [mulcmu/esphome-marlin-uart#6]
Reported in https://github.com/mulcmu/esphome-marlin-uart/issues/1#issuecomment-1828170629

**Comment by mulcmu** [comment]
@fran6120 changes for esp-idf have been implemented [here](https://github.com/mulcmu/esphome-marlin-uart/blob/string-changes/esphome-marlin-uart.h).  I've tested on my printer with ESP8266 and it compiles okay for ESP32 with esp-idf framework. 
Could you give it a test on your setup?

**Comment by fran6120** [comment]
@mulcmu Sorry for the delay!!

I haven't been able to do much testing yet, but at the moment it compiles and runs perfectly using the esp-idf framework.


Arduino framework:
```
RAM: [= ] 14.1% (used 46104 bytes from 327680 bytes)
Flash: [====== ] 61.2% (used 1123297 bytes from 1835008 bytes)
```

esp-idf framework:
```
RAM:   [=         ]   9.0% (used 29396 bytes from 327680 bytes)
Flash: [=====     ]  52.5% (used 963049 bytes from 1835008 bytes)
```

Although it doesn't seem like much, in my opinion at least, with esp-idf with the same configuration I notice the camera is more fluid compared to the Arduino framework.

Thank you so much!

**Comment by mulcmu** [comment]
@fran6120   Thanks for testing!  

Could you post your sample .yaml configuration for the ESP32 camera?  Might help some others in the future.
